name: DiscordWhitelistPlugin
main: com.vagsinhooo.whitelist.WhitelistFromDiscord
version: 1.0.0
api-version: "1.20"
author: vags inhooo
description: Adds/removes players from whitelist via Discord messages through DiscordSRV.
depend: [DiscordSRV]
